# 暴露端口号
server:
  port: 8040

# 自定义数据库配置信息
databaseInfo:
  ip: localhost:3306
  database: myweb
  params: useUnicode=true&&characterEncoding=UTF-8&&serverTimezone=UTC
  username: root
  password: wjr9422325vm

spring:
  application:
    name: MYWEB
  # 配置mysql数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${databaseInfo.ip}/${databaseInfo.database}?${databaseInfo.params}
    username: ${databaseInfo.username}
    password: ${databaseInfo.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 10
    max-idle: 5
    min-idle: 5
    initial-size: 5
    max-wait: 10000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  # 配置数据持久层框架
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # 配置Redis
  #  redis:
  #    database: 0
  #    host: default.lazyr.top
  #    port: 6379
  #    lettuce:
  #      pool:
  #        max-active: 8
  #        max-wait: -1
  #        max-idle: 8
  #        min-idle: 0
  #    timeout: 5000
  # 配置邮箱
  mail:
    password: rldihiedietldjca
    username: lazywjr@foxmail.com
    host: smtp.qq.com
    default-encoding: utf-8

# 配置Swagger中显示的项目信息
project:
  show: true
  host: localhost:${server.port}
  groupId: top.lazyr
  artifactId: lazy_web_backend
  version: 1.0-SNAPSHOT
  name: lazy_web_backend
  description: This is a personal web
  url: https://spring.io/projects/spring-boot/lazy_web_backend

